### ISSUE TITLE
Unable to attach psycopg2-py36 layer for us-east-1

### ISSUE THREAD

**Issue by ifeins** [revmischa/psycopg2-lambda-layer#1]
I have an AWS Lambda function that runs in `us-east-1` with a runtime of `python 3.6`

When I attempt to attach the py36 us-east-1 layer using the ARN provided in the README (`arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py36:2`) I get the following error in AWS Lambda Console: "You are not authorized to perform: lambda:GetLayerVersion".

However if I attempt to attach the py37 us-east-1 layer (arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py37:2) it works successfully.

This doesn't help me as my runtime is 3.6 and so I need the py36 layer.

**Comment by revmischa** [comment]
okay can you give `arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py36:3` a try please?

**Comment by ifeins** [comment]
@revmischa It worked, thank you 👍 
Can you also update the documentation to include the new ARN?

**Comment by revmischa** [comment]
Okay done, thanks!
